version: '3'
services:
  haproxy:
    image:  docker.ghiasi.me:5000/haproxy:alpine
    container_name: haproxy
    network_mode: host
    restart: always
    environment:
    - TZ=Asia/Tehran
    volumes:
    - ./haproxy.cfg/:/usr/local/etc/haproxy/haproxy.cfg
    
